# Copyright (c) 2026 ad25343 — https://github.com/ad25343/InformaticaConversion
# Licensed under CC BY-NC 4.0. Commercial use requires written permission.
"""
STEP 7 — Convert dispatcher.

ConversionAgent.convert() and the module-level convert() shim both live here.
They select the right system prompt (dbt / PySpark / Python) and orchestrate
the Claude call, output parsing, and artifact injection.
"""
from __future__ import annotations

import re
from typing import Optional

from ._common import (
    MODEL,
    make_client,
    BaseAgent,
    build_security_context_block,
    CONVERSION_PROMPT,
    _ETL_LIBRARY_SECTION,
    _build_flag_handling_section,
    _build_manifest_override_section,
    _validate_conversion_files,
)
from ._pyspark import PYSPARK_SYSTEM
from ._dbt import DBT_SYSTEM, build_dbt_runtime_artifacts
from ._python import PYTHON_SYSTEM
from ...models.schemas import (
    StackAssignment, ConversionOutput, TargetStack,
    SessionParseReport, ComplexityReport,
)
from ..classifier_agent import _build_pattern_yaml_skeleton


# ─────────────────────────────────────────────────────────────────────────────
# etl_patterns run.py builder (unchanged from original)
# ─────────────────────────────────────────────────────────────────────────────

def _build_etl_patterns_run_script(mapping_name: str, pattern: str) -> str:
    """
    Return a minimal run.py that executes an etl_patterns config YAML.
    This gives the developer a ready-to-run entry point alongside the
    generated config skeleton.
    """
    slug = mapping_name.lower().replace(" ", "_")
    return (
        "#!/usr/bin/env python\n"
        '"""run.py — Execute an etl_patterns config YAML.\n\n'
        "Generated by the Informatica Conversion Tool (v2.16.0-phase5).\n\n"
        "Usage:\n"
        f"    python run.py config/{slug}.yaml\n\n"
        "Prerequisites:\n"
        "    pip install -e etl_patterns/    # install the pattern library\n"
        '"""\n'
        "from __future__ import annotations\n"
        "import sys\n"
        "import logging\n"
        "from etl_patterns import config_loader\n\n"
        'logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s %(message)s")\n\n'
        'if __name__ == "__main__":\n'
        "    if len(sys.argv) < 2:\n"
        f'        print("Usage: python run.py <config_yaml_path>")\n'
        "        sys.exit(1)\n"
        "    config_path = sys.argv[1]\n"
        "    result = config_loader.run(config_path)\n"
        '    print(f"Result: {result}")\n'
        '    sys.exit(0 if result.get("status") == "success" else 1)\n'
    )


# ─────────────────────────────────────────────────────────────────────────────
# YAML config artifacts helpers
# ─────────────────────────────────────────────────────────────────────────────

def _append_parameters_block(lines: list[str], spr: SessionParseReport) -> None:
    """Append the resolved-parameters block to lines (mutates in place)."""
    if not spr.parameters:
        return
    lines += ["", "# Resolved parameters (from parameter file)", "parameters:"]
    for p in spr.parameters:
        safe_val = str(p.value).replace('"', '\\"')
        lines.append(f'  {p.name}: "{safe_val}"  # scope: {p.scope}')


def _append_unresolved_vars_block(lines: list[str], spr: SessionParseReport) -> None:
    """Append the unresolved-variables block to lines (mutates in place)."""
    if not spr.unresolved_variables:
        return
    lines += ["", "# Unresolved variables — values must be supplied at runtime", "unresolved_variables:"]
    for v in spr.unresolved_variables:
        lines.append(f"  {v}: <fill_in>")


def _build_connections_yaml(spr: SessionParseReport) -> str:
    """Build connections.yaml content from session parse report."""
    sc = spr.session_config
    lines: list[str] = [
        "# connections.yaml — generated by Informatica Conversion Tool v1.1",
        f"# Session: {sc.session_name if sc else 'N/A'}",
        f"# Workflow: {sc.workflow_name if sc else 'N/A'}",
        "#",
        "# Fill in the <placeholders> before use.",
        "",
        "connections:",
    ]

    if sc and sc.connections:
        lines.extend(_build_connection_entries(sc.connections))
    else:
        lines.append("  # No connections extracted from Workflow XML")

    _append_parameters_block(lines, spr)
    _append_unresolved_vars_block(lines, spr)
    return "\n".join(lines) + "\n"


def _build_single_connection_lines(conn) -> list[str]:
    """Build YAML lines for a single connection object."""
    lines = [f"  {conn.transformation_name}:", f"    role: {conn.role}"]
    optional_str_fields = [
        ("connection_name", conn.connection_name),
        ("connection_type", conn.connection_type),
        ("file_name", conn.file_name),
        ("file_dir", conn.file_dir),
    ]
    for field_name, value in optional_str_fields:
        if value:
            lines.append(f"    {field_name}: {value}")
    if conn.connection_type and conn.connection_type.upper() in ("RELATIONAL", "ODBC"):
        lines += ["    jdbc_url: <fill_in>", "    username: <fill_in>", "    password: <fill_in>"]
    return lines


def _build_connection_entries(connections: list) -> list[str]:
    """Build YAML lines for each connection (deduped by connection_key)."""
    lines: list[str] = []
    seen: set[str] = set()
    for conn in connections:
        conn_key = conn.connection_name or conn.transformation_name
        if conn_key in seen:
            continue
        seen.add(conn_key)
        lines.extend(_build_single_connection_lines(conn))
    return lines


def _build_runtime_config_yaml(spr: SessionParseReport) -> str:
    """Build runtime_config.yaml content from session parse report."""
    sc = spr.session_config
    lines: list[str] = [
        "# runtime_config.yaml — generated by Informatica Conversion Tool v1.1",
        f"# Session: {sc.session_name if sc else 'N/A'}",
        f"# Workflow: {sc.workflow_name if sc else 'N/A'}",
        "",
        "session:",
    ]

    if sc:
        lines.extend(_build_session_config_lines(sc))
    else:
        lines.append("  # No session config extracted from Workflow XML")

    return "\n".join(lines) + "\n"


def _append_sql_block(lines: list[str], label: str, sql: str) -> None:
    """Append a multi-line SQL block to lines (mutates in place)."""
    if not sql:
        return
    lines += ["", f"  {label}: |"]
    lines.extend(f"    {ln}" for ln in sql.splitlines())


def _build_session_config_lines(sc) -> list[str]:
    """Build YAML lines for session config fields."""
    lines = [
        f"  name: {sc.session_name}",
        f"  mapping: {sc.mapping_name}",
        f"  workflow: {sc.workflow_name}",
    ]
    # Scalar optionals
    scalar_fields = [
        ("commit_interval", sc.commit_interval),
        ("error_threshold", sc.error_threshold),
        ("reject_filename", sc.reject_filename),
        ("reject_filedir", sc.reject_filedir),
    ]
    for field_name, value in scalar_fields:
        if value is not None:
            lines.append(f"  {field_name}: {value}")
    _append_sql_block(lines, "pre_session_sql", sc.pre_session_sql or "")
    _append_sql_block(lines, "post_session_sql", sc.post_session_sql or "")
    return lines


def _build_yaml_artifacts(spr: SessionParseReport) -> dict[str, str]:
    """
    Generate connections.yaml and runtime_config.yaml from Step 0 session data.
    Returns a dict of {filename: yaml_content}.
    """
    return {
        "config/connections.yaml": _build_connections_yaml(spr),
        "config/runtime_config.yaml": _build_runtime_config_yaml(spr),
    }


# ─────────────────────────────────────────────────────────────────────────────
# _convert_impl helpers
# ─────────────────────────────────────────────────────────────────────────────

_SYSTEM_MAP = {
    TargetStack.PYSPARK: PYSPARK_SYSTEM,
    TargetStack.DBT:     DBT_SYSTEM,
    TargetStack.PYTHON:  PYTHON_SYSTEM,
    TargetStack.HYBRID:  PYSPARK_SYSTEM,  # Default to PySpark for hybrid MVP
}


def _build_approved_fixes_section(accepted_fixes: list[str] | None) -> str:
    """Build the reviewer-approved fixes prompt section."""
    if not accepted_fixes:
        return ""
    numbered = "\n".join(f"{i+1}. {fix}" for i, fix in enumerate(accepted_fixes))
    return (
        f"\n## Reviewer-Approved Fixes — Apply These Exactly\n"
        f"The human reviewer has reviewed the verification flags and approved the following "
        f"specific fixes. You MUST apply each one precisely as described — do not skip, "
        f"paraphrase, or generalise:\n\n{numbered}\n\n"
    )


def _build_security_fix_section(security_findings: list[dict] | None) -> str:
    """Build the security findings prompt section."""
    if not security_findings:
        return ""
    finding_lines = [
        _format_security_finding(i, f)
        for i, f in enumerate(security_findings, 1)
    ]
    return (
        "\n## Security Findings — You MUST Fix All of These\n"
        "A human security reviewer rejected the previous code generation and requested fixes. "
        "The EXACT offending code snippets are shown for each finding — you must NOT reproduce "
        "these patterns anywhere in the regenerated code. For each finding, apply the stated "
        "fix or an equivalent secure alternative:\n\n"
        + "\n\n".join(finding_lines)
        + "\n\n"
    )


def _finding_fix_text(fix: str) -> str:
    """Return fix guidance or a default instruction."""
    return fix or "Do not reproduce this pattern in the regenerated code."


def _finding_snippet(location: str, line_ref: str, code: str) -> str:
    """Return a code snippet block if code is non-empty, else empty string."""
    if not code:
        return ""
    return f"\n   Offending code ({location}{line_ref}):\n   ```\n   {code}\n   ```"


def _format_security_finding(idx: int, f: dict) -> str:
    """Format a single security finding entry."""
    sev      = f.get("severity", "UNKNOWN")
    ftype    = f.get("test_name") or f.get("finding_type", "security issue")
    location = f.get("filename") or f.get("location", "")
    desc     = f.get("text") or f.get("description", "")
    fix      = f.get("remediation", "")
    code     = f.get("code", "").strip()
    line     = f.get("line")
    line_ref = f" line {line}" if line else ""
    snippet  = _finding_snippet(location, line_ref, code)
    return (
        f"{idx}. [{sev}] {ftype} — {location}{line_ref}\n"
        f"   Issue: {desc}{snippet}\n"
        f"   Fix required: {_finding_fix_text(fix)}"
    )


_BEGIN_PATTERN = re.compile(r"<<<BEGIN_FILE:\s*(.+?)>>>", re.IGNORECASE)
_END_MARKER    = "<<<END_FILE>>>"
_NOTES_BEGIN   = "<<<NOTES>>>"
_NOTES_END     = "<<<END_NOTES>>>"


def _extract_files_from_delimiters(raw: str) -> tuple[dict[str, str], list[str]]:
    """Extract file contents from delimiter-format Claude output."""
    files: dict[str, str] = {}
    notes: list[str] = []
    pos = 0
    while pos < len(raw):
        m = _BEGIN_PATTERN.search(raw, pos)
        if not m:
            break
        fname = m.group(1).strip()
        content_start = m.end()
        end_pos = raw.find(_END_MARKER, content_start)
        if end_pos == -1:
            files[fname] = raw[content_start:].lstrip("\n")
            notes.append(f"File '{fname}' appears truncated (no END_FILE marker found).")
            break
        files[fname] = raw[content_start:end_pos].lstrip("\n").rstrip("\n")
        pos = end_pos + len(_END_MARKER)
    return files, notes


def _extract_notes_from_raw(raw: str) -> list[str]:
    """Extract the NOTES section from Claude delimiter output."""
    n_start = raw.find(_NOTES_BEGIN)
    if n_start == -1:
        return []
    n_end = raw.find(_NOTES_END, n_start)
    notes_text = raw[n_start + len(_NOTES_BEGIN): n_end if n_end != -1 else len(raw)].strip()
    return [ln.strip("- •").strip() for ln in notes_text.splitlines() if ln.strip("- •").strip()]


def _parse_delimiter_output(raw: str) -> tuple[dict[str, str], list[str], bool]:
    """
    Parse Claude's delimiter-format output into files dict and notes list.
    Returns (files, notes, parsed_ok).
    """
    files, file_notes = _extract_files_from_delimiters(raw)
    notes = file_notes + _extract_notes_from_raw(raw)
    return files, notes, bool(files)


def _handle_truncation(files: dict[str, str], notes: list[str], stop_reason: str, stack, raw: str) -> None:
    """Mutate notes in-place: add truncation/fallback warnings."""
    if not files:
        files[f"converted_{stack.value.lower()}_raw.txt"] = raw
        notes.append(
            "Conversion output did not use the expected file delimiter format. "
            "Raw response saved. Re-running the job should resolve this."
        )
        return
    if stop_reason == "max_tokens":
        notes.append(
            "Response reached the token limit — one or more files may be truncated. "
            "Review the last file carefully. If incomplete, re-run the job."
        )


def _inject_yaml_artifacts(
    files: dict[str, str],
    notes: list[str],
    session_parse_report: Optional[SessionParseReport],
) -> None:
    """Inject YAML config artifacts into files if session data is available."""
    if not (session_parse_report and session_parse_report.session_config):
        return
    try:
        yaml_files = _build_yaml_artifacts(session_parse_report)
        files.update(yaml_files)
        notes.append(
            f"v1.1: Generated {len(yaml_files)} config artifact(s): "
            + ", ".join(yaml_files.keys())
        )
    except Exception as e:
        notes.append(f"v1.1: YAML artifact generation failed (non-blocking): {e}")


def _inject_dbt_artifacts(
    files: dict[str, str],
    notes: list[str],
    stack,
    stack_assignment: StackAssignment,
    session_parse_report: Optional[SessionParseReport],
) -> None:
    """Inject dbt runtime artifacts if stack is DBT."""
    if stack != TargetStack.DBT:
        return
    try:
        dbt_rt = build_dbt_runtime_artifacts(stack_assignment, session_parse_report)
        files.update(dbt_rt)
        notes.append(
            f"v2.7: Generated dbt runtime artifacts: {', '.join(dbt_rt.keys())}. "
            "Set the environment variables in profiles.yml before running."
        )
    except Exception as e:
        notes.append(f"v2.7: dbt runtime artifact generation failed (non-blocking): {e}")


def _inject_etl_pattern_artifacts(
    files: dict[str, str],
    notes: list[str],
    stack_assignment: StackAssignment,
    complexity_report: Optional[ComplexityReport],
    graph: dict,
) -> None:
    """Inject etl_patterns config skeleton if a pattern was detected."""
    if not (complexity_report and complexity_report.suggested_pattern):
        return
    if complexity_report.pattern_confidence in (None, "NONE"):
        return
    try:
        mapping_slug = stack_assignment.mapping_name.lower().replace(" ", "_")
        pattern_yaml = _build_pattern_yaml_skeleton(
            pattern=complexity_report.suggested_pattern,
            mapping_name=stack_assignment.mapping_name,
            graph=graph,
        )
        config_key = f"config/{mapping_slug}.yaml"
        files[config_key] = pattern_yaml
        files["run.py"] = _build_etl_patterns_run_script(
            mapping_name=stack_assignment.mapping_name,
            pattern=complexity_report.suggested_pattern,
        )
        notes.append(
            f"v2.16.0 (etl_patterns): Pattern '{complexity_report.suggested_pattern}' "
            f"detected with {complexity_report.pattern_confidence} confidence. "
            f"Starter config emitted to '{config_key}'. "
            "Install etl_patterns (`pip install -e etl_patterns/`) and run: "
            f"python run.py {config_key}"
        )
    except Exception as e:
        notes.append(
            f"v2.16.0 (etl_patterns): config skeleton generation failed (non-blocking): {e}"
        )


def _norm_flags(verification_flags) -> list:
    """Normalise verification flags to plain dicts (model_dump if Pydantic, else as-is)."""
    return [f.model_dump() if hasattr(f, "model_dump") else f for f in (verification_flags or [])]


# ─────────────────────────────────────────────────────────────────────────────
# Core conversion logic
# ─────────────────────────────────────────────────────────────────────────────

async def _convert_impl(
    stack_assignment: StackAssignment,
    documentation_md: str,
    graph: dict,
    accepted_fixes: list[str] | None = None,
    security_findings: list[dict] | None = None,
    session_parse_report: Optional[SessionParseReport] = None,
    verification_flags: list[dict] | None = None,
    manifest_overrides: list[dict] | None = None,
    complexity_report: Optional[ComplexityReport] = None,
) -> ConversionOutput:
    """
    Generate converted code for the assigned target stack.

    accepted_fixes      — reviewer-approved code-level fixes from Gate 1 (Step 5)
    security_findings   — security scan findings from a previous round (REQUEST_FIX path);
                          Claude must address every listed finding in this regeneration
    verification_flags  — flags from Step 4 verification; Claude auto-handles each
                          (stubs, TODOs, config extraction) so the conversion is never blocked
                          by issues that can be addressed in code
    manifest_overrides  — reviewer-supplied overrides from the pre-conversion manifest xlsx;
                          these take precedence over tool-inferred connections for any
                          ambiguous or unmapped items
    """
    from .._client import call_claude_with_retry
    client = make_client()
    stack = stack_assignment.assigned_stack

    # Build optional prompt sections
    approved_fixes_section = _build_approved_fixes_section(accepted_fixes)
    security_fix_section   = _build_security_fix_section(security_findings)

    try:
        security_context = build_security_context_block()
    except Exception:
        security_context = ""  # never block a conversion due to KB read failure

    flag_handling_section     = _build_flag_handling_section(_norm_flags(verification_flags))
    manifest_override_section = _build_manifest_override_section(manifest_overrides or [])

    # Only inject etl_library_section for PySpark/Python — dbt uses macros, not Python imports
    _etl_lib = _ETL_LIBRARY_SECTION if stack in (TargetStack.PYSPARK, TargetStack.PYTHON, TargetStack.HYBRID) else ""

    prompt = CONVERSION_PROMPT.format(
        stack=stack.value,
        rationale=stack_assignment.rationale,
        security_context=security_context,
        approved_fixes_section=approved_fixes_section + security_fix_section,
        flag_handling_section=flag_handling_section,
        manifest_override_section=manifest_override_section,
        etl_library_section=_etl_lib,
        documentation_md=documentation_md[:30_000],
    )

    message = await call_claude_with_retry(
        client,
        model=MODEL,
        max_tokens=32000,
        system=_SYSTEM_MAP.get(stack, PYSPARK_SYSTEM),
        messages=[{"role": "user", "content": prompt}],
    )

    raw         = message.content[0].text.strip()
    stop_reason = message.stop_reason  # "end_turn" | "max_tokens"

    files, notes, parsed_ok = _parse_delimiter_output(raw)
    _handle_truncation(files, notes, stop_reason, stack, raw)
    parsed_ok = bool(files) and "converted_" + stack.value.lower() + "_raw.txt" not in files

    # Non-blocking content validation
    notes.extend(_validate_conversion_files(files, stack))

    # Artifact injection
    _inject_yaml_artifacts(files, notes, session_parse_report)
    _inject_dbt_artifacts(files, notes, stack, stack_assignment, session_parse_report)
    _inject_etl_pattern_artifacts(files, notes, stack_assignment, complexity_report, graph)

    return ConversionOutput(
        mapping_name=stack_assignment.mapping_name,
        target_stack=stack,
        files=files,
        notes=notes,
        parse_ok=parsed_ok,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Public API: ConversionAgent class + module-level convert() shim
# ─────────────────────────────────────────────────────────────────────────────

class ConversionAgent(BaseAgent):

    async def convert(
        self,
        stack_assignment: StackAssignment,
        documentation_md: str,
        graph: dict,
        accepted_fixes: list[str] | None = None,
        security_findings: list[dict] | None = None,
        session_parse_report: Optional[SessionParseReport] = None,
        verification_flags: list[dict] | None = None,
        manifest_overrides: list[dict] | None = None,
        complexity_report: Optional[ComplexityReport] = None,
    ) -> ConversionOutput:
        return await _convert_impl(
            stack_assignment, documentation_md, graph,
            accepted_fixes, security_findings, session_parse_report,
            verification_flags, manifest_overrides, complexity_report,
        )


async def convert(
    stack_assignment: StackAssignment,
    documentation_md: str,
    graph: dict,
    accepted_fixes: list[str] | None = None,
    security_findings: list[dict] | None = None,
    session_parse_report: Optional[SessionParseReport] = None,
    verification_flags: list[dict] | None = None,
    manifest_overrides: list[dict] | None = None,
    complexity_report: Optional[ComplexityReport] = None,
) -> ConversionOutput:
    """Module-level backward-compat shim — keeps orchestrator.py call sites unchanged."""
    return await ConversionAgent().convert(
        stack_assignment, documentation_md, graph,
        accepted_fixes, security_findings, session_parse_report,
        verification_flags, manifest_overrides, complexity_report,
    )
