# Copyright (c) 2026 ad25343 — https://github.com/ad25343/InformaticaConversion
# Licensed under CC BY-NC 4.0. Commercial use requires written permission.
"""
STEP 7 — Convert dispatcher.

ConversionAgent.convert() and the module-level convert() shim both live here.
They select the right system prompt (dbt / PySpark / Python) and orchestrate
the Claude call, output parsing, and artifact injection.
"""
from __future__ import annotations

import re
from typing import Optional

from ._common import (
    MODEL,
    make_client,
    BaseAgent,
    build_security_context_block,
    CONVERSION_PROMPT,
    _build_flag_handling_section,
    _build_manifest_override_section,
    _validate_conversion_files,
)
from ._pyspark import PYSPARK_SYSTEM
from ._dbt import DBT_SYSTEM, build_dbt_runtime_artifacts
from ._python import PYTHON_SYSTEM
from ...models.schemas import (
    StackAssignment, ConversionOutput, TargetStack,
    SessionParseReport, ComplexityReport,
)
from ..classifier_agent import _build_pattern_yaml_skeleton


# ─────────────────────────────────────────────────────────────────────────────
# etl_patterns run.py builder (unchanged from original)
# ─────────────────────────────────────────────────────────────────────────────

def _build_etl_patterns_run_script(mapping_name: str, pattern: str) -> str:
    """
    Return a minimal run.py that executes an etl_patterns config YAML.
    This gives the developer a ready-to-run entry point alongside the
    generated config skeleton.
    """
    slug = mapping_name.lower().replace(" ", "_")
    return (
        "#!/usr/bin/env python\n"
        '"""run.py — Execute an etl_patterns config YAML.\n\n'
        "Generated by the Informatica Conversion Tool (v2.16.0-phase5).\n\n"
        "Usage:\n"
        f"    python run.py config/{slug}.yaml\n\n"
        "Prerequisites:\n"
        "    pip install -e etl_patterns/    # install the pattern library\n"
        '"""\n'
        "from __future__ import annotations\n"
        "import sys\n"
        "import logging\n"
        "from etl_patterns import config_loader\n\n"
        'logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s %(message)s")\n\n'
        'if __name__ == "__main__":\n'
        "    if len(sys.argv) < 2:\n"
        f'        print("Usage: python run.py <config_yaml_path>")\n'
        "        sys.exit(1)\n"
        "    config_path = sys.argv[1]\n"
        "    result = config_loader.run(config_path)\n"
        '    print(f"Result: {result}")\n'
        '    sys.exit(0 if result.get("status") == "success" else 1)\n'
    )


# ─────────────────────────────────────────────────────────────────────────────
# YAML config artifacts (connections.yaml + runtime_config.yaml)
# ─────────────────────────────────────────────────────────────────────────────

def _build_yaml_artifacts(spr: SessionParseReport) -> dict[str, str]:
    """
    Generate connections.yaml and runtime_config.yaml from Step 0 session data.
    Returns a dict of {filename: yaml_content}.
    """
    artifacts: dict[str, str] = {}

    sc = spr.session_config

    # ── connections.yaml ──────────────────────────────────────────────────
    conn_lines: list[str] = [
        "# connections.yaml — generated by Informatica Conversion Tool v1.1",
        f"# Session: {sc.session_name if sc else 'N/A'}",
        f"# Workflow: {sc.workflow_name if sc else 'N/A'}",
        "#",
        "# Fill in the <placeholders> before use.",
        "",
        "connections:",
    ]

    if sc and sc.connections:
        seen: set[str] = set()
        for conn in sc.connections:
            conn_key = conn.connection_name or conn.transformation_name
            if conn_key in seen:
                continue
            seen.add(conn_key)
            conn_lines.append(f"  {conn.transformation_name}:")
            conn_lines.append(f"    role: {conn.role}")
            if conn.connection_name:
                conn_lines.append(f"    connection_name: {conn.connection_name}")
            if conn.connection_type:
                conn_lines.append(f"    connection_type: {conn.connection_type}")
            if conn.file_name:
                conn_lines.append(f"    file_name: {conn.file_name}")
            if conn.file_dir:
                conn_lines.append(f"    file_dir: {conn.file_dir}")
            # Placeholder for actual DB connection string
            if conn.connection_type and conn.connection_type.upper() in ("RELATIONAL", "ODBC"):
                conn_lines.append("    jdbc_url: <fill_in>")
                conn_lines.append("    username: <fill_in>")
                conn_lines.append("    password: <fill_in>")
    else:
        conn_lines.append("  # No connections extracted from Workflow XML")

    if spr.parameters:
        conn_lines += [
            "",
            "# Resolved parameters (from parameter file)",
            "parameters:",
        ]
        for p in spr.parameters:
            # Escape any special chars in YAML value
            safe_val = str(p.value).replace('"', '\\"')
            conn_lines.append(f'  {p.name}: "{safe_val}"  # scope: {p.scope}')

    if spr.unresolved_variables:
        conn_lines += [
            "",
            "# Unresolved variables — values must be supplied at runtime",
            "unresolved_variables:",
        ]
        for v in spr.unresolved_variables:
            conn_lines.append(f"  {v}: <fill_in>")

    artifacts["config/connections.yaml"] = "\n".join(conn_lines) + "\n"

    # ── runtime_config.yaml ───────────────────────────────────────────────
    rt_lines: list[str] = [
        "# runtime_config.yaml — generated by Informatica Conversion Tool v1.1",
        f"# Session: {sc.session_name if sc else 'N/A'}",
        f"# Workflow: {sc.workflow_name if sc else 'N/A'}",
        "",
        "session:",
    ]

    if sc:
        rt_lines.append(f"  name: {sc.session_name}")
        rt_lines.append(f"  mapping: {sc.mapping_name}")
        rt_lines.append(f"  workflow: {sc.workflow_name}")

        if sc.commit_interval is not None:
            rt_lines.append(f"  commit_interval: {sc.commit_interval}")
        if sc.error_threshold is not None:
            rt_lines.append(f"  error_threshold: {sc.error_threshold}")
        if sc.reject_filename:
            rt_lines.append(f"  reject_filename: {sc.reject_filename}")
        if sc.reject_filedir:
            rt_lines.append(f"  reject_filedir: {sc.reject_filedir}")
        if sc.pre_session_sql:
            rt_lines += ["", "  pre_session_sql: |"]
            for ln in sc.pre_session_sql.splitlines():
                rt_lines.append(f"    {ln}")
        if sc.post_session_sql:
            rt_lines += ["", "  post_session_sql: |"]
            for ln in sc.post_session_sql.splitlines():
                rt_lines.append(f"    {ln}")
    else:
        rt_lines.append("  # No session config extracted from Workflow XML")

    artifacts["config/runtime_config.yaml"] = "\n".join(rt_lines) + "\n"

    return artifacts


# ─────────────────────────────────────────────────────────────────────────────
# Core conversion logic
# ─────────────────────────────────────────────────────────────────────────────

async def _convert_impl(
    stack_assignment: StackAssignment,
    documentation_md: str,
    graph: dict,
    accepted_fixes: list[str] | None = None,
    security_findings: list[dict] | None = None,
    session_parse_report: Optional[SessionParseReport] = None,
    verification_flags: list[dict] | None = None,
    manifest_overrides: list[dict] | None = None,
    complexity_report: Optional[ComplexityReport] = None,
) -> ConversionOutput:
    """
    Generate converted code for the assigned target stack.

    accepted_fixes      — reviewer-approved code-level fixes from Gate 1 (Step 5)
    security_findings   — security scan findings from a previous round (REQUEST_FIX path);
                          Claude must address every listed finding in this regeneration
    verification_flags  — flags from Step 4 verification; Claude auto-handles each
                          (stubs, TODOs, config extraction) so the conversion is never blocked
                          by issues that can be addressed in code
    manifest_overrides  — reviewer-supplied overrides from the pre-conversion manifest xlsx;
                          these take precedence over tool-inferred connections for any
                          ambiguous or unmapped items
    """
    from .._client import call_claude_with_retry
    client = make_client()
    stack = stack_assignment.assigned_stack

    system_map = {
        TargetStack.PYSPARK: PYSPARK_SYSTEM,
        TargetStack.DBT:     DBT_SYSTEM,
        TargetStack.PYTHON:  PYTHON_SYSTEM,
        TargetStack.HYBRID:  PYSPARK_SYSTEM,  # Default to PySpark for hybrid MVP
    }

    # Build the optional "Reviewer-Approved Fixes" section (from Gate 1)
    if accepted_fixes:
        numbered = "\n".join(f"{i+1}. {fix}" for i, fix in enumerate(accepted_fixes))
        approved_fixes_section = (
            f"\n## Reviewer-Approved Fixes — Apply These Exactly\n"
            f"The human reviewer has reviewed the verification flags and approved the following "
            f"specific fixes. You MUST apply each one precisely as described — do not skip, "
            f"paraphrase, or generalise:\n\n{numbered}\n\n"
        )
    else:
        approved_fixes_section = ""

    # Build the optional "Security Findings to Fix" section (from Gate 2 REQUEST_FIX)
    if security_findings:
        finding_lines = []
        for i, f in enumerate(security_findings, 1):
            sev      = f.get("severity", "UNKNOWN")
            ftype    = f.get("test_name") or f.get("finding_type", "security issue")
            location = f.get("filename") or f.get("location", "")
            desc     = f.get("text") or f.get("description", "")
            fix      = f.get("remediation", "")
            code     = f.get("code", "").strip()
            line     = f.get("line")
            line_ref = f" line {line}" if line else ""
            snippet  = f"\n   Offending code ({location}{line_ref}):\n   ```\n   {code}\n   ```" if code else ""
            finding_lines.append(
                f"{i}. [{sev}] {ftype} — {location}{line_ref}\n"
                f"   Issue: {desc}{snippet}\n"
                f"   Fix required: {fix if fix else 'Do not reproduce this pattern in the regenerated code.'}"
            )
        security_fix_section = (
            "\n## Security Findings — You MUST Fix All of These\n"
            "A human security reviewer rejected the previous code generation and requested fixes. "
            "The EXACT offending code snippets are shown for each finding — you must NOT reproduce "
            "these patterns anywhere in the regenerated code. For each finding, apply the stated "
            "fix or an equivalent secure alternative:\n\n"
            + "\n\n".join(finding_lines)
            + "\n\n"
        )
    else:
        security_fix_section = ""

    # Load standing rules + learned patterns from the knowledge base
    try:
        security_context = build_security_context_block()
    except Exception:
        security_context = ""  # never block a conversion due to KB read failure

    # Build verification flag auto-handling section
    flag_handling_section = _build_flag_handling_section(
        [f.model_dump() if hasattr(f, "model_dump") else f for f in (verification_flags or [])]
    )

    # Build manifest overrides section — reviewer-confirmed connections and gap resolutions
    manifest_override_section = _build_manifest_override_section(manifest_overrides or [])

    prompt = CONVERSION_PROMPT.format(
        stack=stack.value,
        rationale=stack_assignment.rationale,
        security_context=security_context,
        approved_fixes_section=approved_fixes_section + security_fix_section,
        flag_handling_section=flag_handling_section,
        manifest_override_section=manifest_override_section,
        documentation_md=documentation_md[:30_000],
    )

    message = await call_claude_with_retry(
        client,
        model=MODEL,
        max_tokens=32000,
        system=system_map.get(stack, PYSPARK_SYSTEM),
        messages=[{"role": "user", "content": prompt}],
    )

    raw = message.content[0].text.strip()
    stop_reason = message.stop_reason  # "end_turn" | "max_tokens"

    # ── Parse delimiter format ─────────────────────────────────────────────
    # Format: <<<BEGIN_FILE: path>>>...content...<<<END_FILE>>>
    notes: list[str] = []
    files: dict[str, str] = {}
    parsed_ok = False

    begin_pattern = re.compile(r"<<<BEGIN_FILE:\s*(.+?)>>>", re.IGNORECASE)
    end_marker = "<<<END_FILE>>>"
    notes_begin = "<<<NOTES>>>"
    notes_end = "<<<END_NOTES>>>"

    pos = 0
    while pos < len(raw):
        m = begin_pattern.search(raw, pos)
        if not m:
            break
        fname = m.group(1).strip()
        content_start = m.end()
        end_pos = raw.find(end_marker, content_start)
        if end_pos == -1:
            # Truncated — take everything remaining as the file content
            content = raw[content_start:].lstrip("\n")
            files[fname] = content
            notes.append(f"File '{fname}' appears truncated (no END_FILE marker found).")
            break
        content = raw[content_start:end_pos].lstrip("\n").rstrip("\n")
        files[fname] = content
        pos = end_pos + len(end_marker)

    # Extract NOTES section
    n_start = raw.find(notes_begin)
    if n_start != -1:
        n_end = raw.find(notes_end, n_start)
        notes_text = raw[n_start + len(notes_begin): n_end if n_end != -1 else len(raw)].strip()
        for line in notes_text.splitlines():
            line = line.strip("- •").strip()
            if line:
                notes.append(line)

    if files:
        parsed_ok = True
        if stop_reason == "max_tokens":
            notes.append(
                "Response reached the token limit — one or more files may be truncated. "
                "Review the last file carefully. If incomplete, re-run the job."
            )
    else:
        # Fallback: model didn't use delimiters at all — save raw response
        parsed_ok = False
        files = {f"converted_{stack.value.lower()}_raw.txt": raw}
        notes.append(
            "Conversion output did not use the expected file delimiter format. "
            "Raw response saved. Re-running the job should resolve this."
        )

    # ── GAP #7 — Claude output content validation ─────────────────────────
    # Run non-blocking checks on every generated file.  Issues are added to
    # notes so the reviewer sees them, but they never block the pipeline.
    _validation_issues = _validate_conversion_files(files, stack)
    notes.extend(_validation_issues)

    # ── v1.1: inject YAML config artifacts if session data is available ─────
    if session_parse_report and session_parse_report.session_config:
        try:
            yaml_files = _build_yaml_artifacts(session_parse_report)
            files.update(yaml_files)
            notes.append(
                f"v1.1: Generated {len(yaml_files)} config artifact(s): "
                + ", ".join(yaml_files.keys())
            )
        except Exception as e:
            notes.append(f"v1.1: YAML artifact generation failed (non-blocking): {e}")

    # ── v2.7: inject dbt runtime artifacts (profiles.yml, requirements.txt) ─
    if stack == TargetStack.DBT:
        try:
            dbt_rt = build_dbt_runtime_artifacts(stack_assignment, session_parse_report)
            files.update(dbt_rt)
            notes.append(
                f"v2.7: Generated dbt runtime artifacts: {', '.join(dbt_rt.keys())}. "
                "Set the environment variables in profiles.yml before running."
            )
        except Exception as e:
            notes.append(f"v2.7: dbt runtime artifact generation failed (non-blocking): {e}")

    # ── v2.16.0-phase5: etl_patterns config skeleton ──────────────────────────
    if complexity_report and complexity_report.suggested_pattern and \
            complexity_report.pattern_confidence not in (None, "NONE"):
        try:
            mapping_slug = stack_assignment.mapping_name.lower().replace(" ", "_")
            pattern_yaml = _build_pattern_yaml_skeleton(
                pattern=complexity_report.suggested_pattern,
                mapping_name=stack_assignment.mapping_name,
                graph=graph,
            )
            config_key = f"config/{mapping_slug}.yaml"
            files[config_key] = pattern_yaml

            run_py = _build_etl_patterns_run_script(
                mapping_name=stack_assignment.mapping_name,
                pattern=complexity_report.suggested_pattern,
            )
            files["run.py"] = run_py

            notes.append(
                f"v2.16.0 (etl_patterns): Pattern '{complexity_report.suggested_pattern}' "
                f"detected with {complexity_report.pattern_confidence} confidence. "
                f"Starter config emitted to '{config_key}'. "
                "Install etl_patterns (`pip install -e etl_patterns/`) and run: "
                f"python run.py {config_key}"
            )
        except Exception as e:
            notes.append(
                f"v2.16.0 (etl_patterns): config skeleton generation failed (non-blocking): {e}"
            )

    return ConversionOutput(
        mapping_name=stack_assignment.mapping_name,
        target_stack=stack,
        files=files,
        notes=notes,
        parse_ok=parsed_ok,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Public API: ConversionAgent class + module-level convert() shim
# ─────────────────────────────────────────────────────────────────────────────

class ConversionAgent(BaseAgent):

    async def convert(
        self,
        stack_assignment: StackAssignment,
        documentation_md: str,
        graph: dict,
        accepted_fixes: list[str] | None = None,
        security_findings: list[dict] | None = None,
        session_parse_report: Optional[SessionParseReport] = None,
        verification_flags: list[dict] | None = None,
        manifest_overrides: list[dict] | None = None,
        complexity_report: Optional[ComplexityReport] = None,
    ) -> ConversionOutput:
        return await _convert_impl(
            stack_assignment, documentation_md, graph,
            accepted_fixes, security_findings, session_parse_report,
            verification_flags, manifest_overrides, complexity_report,
        )


async def convert(
    stack_assignment: StackAssignment,
    documentation_md: str,
    graph: dict,
    accepted_fixes: list[str] | None = None,
    security_findings: list[dict] | None = None,
    session_parse_report: Optional[SessionParseReport] = None,
    verification_flags: list[dict] | None = None,
    manifest_overrides: list[dict] | None = None,
    complexity_report: Optional[ComplexityReport] = None,
) -> ConversionOutput:
    """Module-level backward-compat shim — keeps orchestrator.py call sites unchanged."""
    return await ConversionAgent().convert(
        stack_assignment, documentation_md, graph,
        accepted_fixes, security_findings, session_parse_report,
        verification_flags, manifest_overrides, complexity_report,
    )
