#!/usr/bin/env python
"""run.py — Execute an etl_patterns config YAML.

Generated by the Informatica Conversion Tool (v2.16.0-phase5).

Usage:
    python run.py config/m_fct_atm_transactions_load.yaml

Prerequisites:
    pip install -e etl_patterns/    # install the pattern library
"""
from __future__ import annotations
import sys
import logging
from etl_patterns import config_loader

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s %(message)s")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python run.py <config_yaml_path>")
        sys.exit(1)
    config_path = sys.argv[1]
    result = config_loader.run(config_path)
    print(f"Result: {result}")
    sys.exit(0 if result.get("status") == "success" else 1)
