# Copyright (c) 2026 ad25343 — https://github.com/ad25343/InformaticaConversion
# Licensed under CC BY-NC 4.0. Commercial use requires written permission.
"""
boundary_tests.py — Expression Boundary Test Generator (Phase 2, Component A)
==============================================================================

Scans Expression transformations in a parsed Informatica graph for high-risk
function categories and generates a pytest file with @pytest.mark.parametrize
stubs covering known Informatica-vs-target semantic differences.

Public API
----------
  generate_boundary_tests(graph, mapping_name) -> str
"""
from __future__ import annotations
import re
from datetime import datetime, timezone


# ─────────────────────────────────────────────────────────────────────────────
# Detection patterns for high-risk Informatica expression categories
# ─────────────────────────────────────────────────────────────────────────────
_EXPR_PATTERNS = [
    ("iif",         re.compile(r"\bIIF\s*\(",        re.IGNORECASE)),
    ("decode",      re.compile(r"\bDECODE\s*\(",     re.IGNORECASE)),
    ("date",        re.compile(
        r"\b(ADD_TO_DATE|DATE_DIFF|TO_DATE|TRUNC)\s*\(", re.IGNORECASE)),
    ("string",      re.compile(
        r"\b(SUBSTR|INSTR|LTRIM|RTRIM|LPAD|RPAD|UPPER|LOWER)\s*\(", re.IGNORECASE)),
    ("aggregation", re.compile(
        r"\b(SUM|AVG|COUNT|MAX|MIN)\s*\(",           re.IGNORECASE)),
]


def generate_boundary_tests(graph: dict, mapping_name: str) -> str:
    """
    Scan Expression transformations in *graph* for high-risk Informatica
    function categories and generate a pytest file with parametrize stubs.

    Parameters
    ----------
    graph : dict
        Parsed Informatica graph.  ``graph["mappings"]`` is a list of mapping
        dicts, each with a ``"transformations"`` list.  Each transformation has
        ``"type"`` (str) and ``"expressions"`` (list of
        ``{"field_name": str, "expression": str}`` **or**
        ``{"port": str, "expression": str}`` dicts).
    mapping_name : str
        Human-readable mapping name used in headers and the output filename.

    Returns
    -------
    str
        Complete content of a pytest ``.py`` file ready to write to disk.
    """
    ts        = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    safe_name = re.sub(r"[^A-Za-z0-9_]", "_", mapping_name).lower()

    # ── Scan graph for expression strings ────────────────────────────────────
    detected: dict[str, list[str]] = {}   # category → [example expr strings]
    for m in graph.get("mappings", []):
        for t in m.get("transformations", []):
            if t.get("type", "") != "Expression":
                continue
            for expr_entry in t.get("expressions", []):
                if isinstance(expr_entry, dict):
                    expr_str = (
                        expr_entry.get("expression", "")
                        or expr_entry.get("expr", "")
                    )
                elif isinstance(expr_entry, str):
                    expr_str = expr_entry
                else:
                    continue
                if not expr_str:
                    continue
                for cat, pattern in _EXPR_PATTERNS:
                    if pattern.search(expr_str):
                        detected.setdefault(cat, [])
                        if len(detected[cat]) < 2:
                            detected[cat].append(expr_str[:80])

    # ── Minimal file when nothing detected ───────────────────────────────────
    if not detected:
        return "\n".join([
            f'"""',
            f"Expression Boundary Tests — {mapping_name}",
            f"Auto-generated by Informatica Conversion Tool (Phase 2)",
            f"Generated: {ts}",
            f"",
            f"No high-risk expression categories (IIF, DECODE, date functions,",
            f"string functions, aggregations) were detected in Expression",
            f"transformations for this mapping.  Add tests here if expressions",
            f"are added during implementation.",
            f'"""',
            f"import pytest",
            f"",
            f"",
            f"def test_placeholder():",
            f'    """Placeholder — replace with real expression tests."""',
            f"    # TODO: add boundary tests once expressions are implemented.",
            f"    pass",
        ])

    # ── Build the test file ───────────────────────────────────────────────────
    lines: list[str] = [
        '"""',
        f"Expression Boundary Tests — {mapping_name}",
        f"Auto-generated by Informatica Conversion Tool (Phase 2)",
        f"Generated: {ts}",
        "",
        "PURPOSE",
        "-------",
        "These tests verify that high-risk Informatica expression categories",
        "behave correctly at boundary / edge-case inputs after translation.",
        "They run in isolation — no database or Informatica environment needed.",
        "",
        "HOW TO RUN",
        "----------",
        f"  pip install pytest",
        f"  pytest tests/test_expressions_{safe_name}.py -v",
        "",
        "FILL IN THE HELPER FUNCTIONS",
        "-----------------------------",
        "Each test calls a helper that wraps the translated expression.",
        "Search for 'FILL IN' comments and replace each stub with a call to",
        "the actual translated function from your generated code.",
        "",
        f"Detected risk categories: {', '.join(detected.keys())}",
        '"""',
        "from __future__ import annotations",
        "import pytest",
        "",
        "",
    ]

    sep = "# " + "─" * 75

    # ── IIF ──────────────────────────────────────────────────────────────────
    if "iif" in detected:
        examples = detected["iif"]
        ex_lines = [f"#   {e}" for e in examples]
        lines += [
            sep,
            "# IIF — Informatica evaluates a NULL condition as FALSE (not NULL propagation).",
            "# Detected example(s):",
            *ex_lines,
            sep,
            "",
            "def _iif_helper(value):",
            '    """',
            "    FILL IN: call the translated IIF expression from your generated code.",
            "    Example: return generated_module.iif_expression(value)",
            "    Replace this stub with the real call.",
            '    """',
            "    raise NotImplementedError('FILL IN: call translated IIF expression')",
            "",
            "",
            "@pytest.mark.parametrize('input_val,expected', [",
            "    (100.0,  100.0),   # TRUE branch — positive value",
            "    (-5.0,   0.0),     # FALSE branch — negative value",
            "    (0.0,    0.0),     # boundary — exactly zero, condition evaluates FALSE",
            "    (None,   0.0),     # NULL input: Informatica treats NULL condition as FALSE",
            "])",
            "def test_iif_null_branch_semantics(input_val, expected):",
            '    """',
            "    IIF NULL handling: Informatica evaluates NULL condition as FALSE,",
            "    taking the FALSE branch — not NULL propagation as in SQL CASE WHEN.",
            "    Verify your translated code matches this behaviour.",
            '    """',
            "    # TODO: call your translated IIF function and assert the result.",
            "    result = _iif_helper(input_val)",
            "    assert result == expected, (",
            "        f'IIF mismatch: input={input_val!r}, got={result!r}, expected={expected!r}'",
            "    )",
            "",
        ]

    # ── DECODE ───────────────────────────────────────────────────────────────
    if "decode" in detected:
        examples = detected["decode"]
        ex_lines = [f"#   {e}" for e in examples]
        lines += [
            sep,
            "# DECODE — case-sensitive matching; NULL input falls through to default.",
            "# Detected example(s):",
            *ex_lines,
            sep,
            "",
            "def _decode_helper(status):",
            '    """',
            "    FILL IN: call the translated DECODE expression from your generated code.",
            "    Example: return generated_module.decode_status(status)",
            '    """',
            "    raise NotImplementedError('FILL IN: call translated DECODE expression')",
            "",
            "",
            "@pytest.mark.parametrize('status,expected', [",
            "    ('A',  'Active'),    # first exact match",
            "    ('I',  'Inactive'),  # second exact match",
            "    ('X',  'Unknown'),   # default — no match",
            "    (None, 'Unknown'),   # NULL → Informatica DECODE falls through to default",
            "    ('a',  'Unknown'),   # case-sensitive: lowercase 'a' != 'A'",
            "])",
            "def test_decode_case_sensitivity_and_null(status, expected):",
            '    """',
            "    DECODE: case-sensitive matching; NULL input falls through to the default.",
            "    Python dict lookups are case-sensitive, but verify None/NULL → default.",
            '    """',
            "    # TODO: call your translated DECODE function and assert the result.",
            "    result = _decode_helper(status)",
            "    assert result == expected, (",
            "        f'DECODE mismatch: input={status!r}, got={result!r}, expected={expected!r}'",
            "    )",
            "",
        ]

    # ── Date functions ────────────────────────────────────────────────────────
    if "date" in detected:
        examples = detected["date"]
        ex_lines = [f"#   {e}" for e in examples]
        lines += [
            sep,
            "# Date functions — month-end rollover and NULL propagation.",
            "# Detected example(s):",
            *ex_lines,
            sep,
            "from datetime import date",
            "",
            "",
            "def _add_to_date_helper(load_date, unit, amount):",
            '    """',
            "    FILL IN: call the translated ADD_TO_DATE expression.",
            "    Example: return generated_module.add_to_date(load_date, unit, amount)",
            '    """',
            "    raise NotImplementedError('FILL IN: call translated ADD_TO_DATE expression')",
            "",
            "",
            "@pytest.mark.parametrize('load_date,unit,amount,expected', [",
            "    (date(2024, 1, 15), 'MM', 1,  date(2024, 2, 15)),   # normal case",
            "    (date(2024, 1, 31), 'MM', 1,  date(2024, 2, 29)),   # month-end rollover (leap year)",
            "    (date(2023, 1, 31), 'MM', 1,  date(2023, 2, 28)),   # month-end rollover (non-leap)",
            "    (date(2024, 12, 31),'MM', 1,  date(2025, 1, 31)),   # year boundary",
            "    (None,              'MM', 1,  None),                 # NULL propagation",
            "])",
            "def test_add_to_date_month_rollover(load_date, unit, amount, expected):",
            '    """',
            "    ADD_TO_DATE: verify month-end rollover matches Informatica semantics.",
            "    NULL input must propagate to NULL output (not raise).",
            '    """',
            "    # TODO: call your translated date function and assert the result.",
            "    result = _add_to_date_helper(load_date, unit, amount)",
            "    assert result == expected, (",
            "        f'ADD_TO_DATE mismatch: input={load_date}, +{amount}{unit}, '",
            "        f'got={result!r}, expected={expected!r}'",
            "    )",
            "",
        ]

    # ── String functions ──────────────────────────────────────────────────────
    if "string" in detected:
        examples = detected["string"]
        ex_lines = [f"#   {e}" for e in examples]
        lines += [
            sep,
            "# String functions — SUBSTR is 1-indexed in Informatica, 0-indexed in Python.",
            "# Detected example(s):",
            *ex_lines,
            sep,
            "",
            "",
            "def _substr_helper(value, start, length):",
            '    """',
            "    FILL IN: call the translated SUBSTR expression.",
            "    CRITICAL: Informatica SUBSTR is 1-indexed; Python slicing is 0-indexed.",
            "    Example: return generated_module.substr(value, start, length)",
            '    """',
            "    raise NotImplementedError('FILL IN: call translated SUBSTR expression')",
            "",
            "",
            "@pytest.mark.parametrize('value,start,length,expected', [",
            "    ('ABCDEF', 1, 3, 'ABC'),   # 1-indexed: positions 1,2,3 → 'ABC'",
            "    ('ABCDEF', 2, 3, 'BCD'),   # offset check",
            "    ('AB',     1, 5, 'AB'),    # length exceeds string — return available chars",
            "    ('',       1, 3, ''),      # empty string boundary",
            "    (None,     1, 3, None),    # NULL propagation",
            "])",
            "def test_substr_one_based_indexing(value, start, length, expected):",
            '    """',
            "    SUBSTR: Informatica is 1-indexed.  The most common mistranslation is",
            "    Python code using str[start:start+length] without subtracting 1 from start.",
            "    SUBSTR('ABCDEF', 1, 3) must return 'ABC', not 'BCD'.",
            '    """',
            "    # TODO: call your translated SUBSTR function and assert the result.",
            "    result = _substr_helper(value, start, length)",
            "    assert result == expected, (",
            "        f'SUBSTR mismatch: ({value!r},{start},{length}), '",
            "        f'got={result!r}, expected={expected!r}'",
            "    )",
            "",
        ]

    # ── Aggregation ───────────────────────────────────────────────────────────
    if "aggregation" in detected:
        examples = detected["aggregation"]
        ex_lines = [f"#   {e}" for e in examples]
        lines += [
            sep,
            "# Aggregation — empty partition must return NULL (not 0) to match Informatica.",
            "# COUNT(*) excludes NULL values in Informatica.",
            "# Detected example(s):",
            *ex_lines,
            sep,
            "import pandas as pd",
            "",
            "",
            "def test_aggregation_empty_partition_returns_null():",
            '    """',
            "    SUM/AVG over an empty partition must return NULL (NaN in pandas),",
            "    never 0.  Use min_count=1 in pandas groupby.sum() to match Informatica.",
            '    """',
            "    # TODO: replace with a call to your translated aggregation expression.",
            "    df = pd.DataFrame({'ACCOUNT_ID': pd.Series([], dtype=str),",
            "                       'AMOUNT':     pd.Series([], dtype=float)})",
            "    result = df.groupby('ACCOUNT_ID')['AMOUNT'].sum(min_count=1).reset_index()",
            "    if not result.empty:",
            "        assert result['AMOUNT'].isna().all(), (",
            "            'Expected NaN/NULL for SUM over empty partition. '",
            "            'Use min_count=1 in pandas groupby.sum().'",
            "        )",
            "",
            "",
            "@pytest.mark.parametrize('values,expected_count', [",
            "    ([1.0, 2.0, None], 2),   # NULL excluded from COUNT(*)",
            "    ([None, None],     0),   # all NULL → COUNT returns 0",
            "    ([],               0),   # empty group → COUNT returns 0",
            "])",
            "def test_count_excludes_nulls(values, expected_count):",
            '    """',
            "    Informatica COUNT(*) excludes NULL values.",
            "    Verify the translated COUNT expression matches this behaviour.",
            '    """',
            "    # TODO: call your translated COUNT expression.",
            "    s = pd.Series(values, dtype=float)",
            "    result = int(s.count())  # pandas .count() excludes NaN — matches Informatica",
            "    assert result == expected_count, (",
            "        f'COUNT mismatch: values={values}, got={result}, expected={expected_count}'",
            "    )",
            "",
        ]

    # ── Footer ────────────────────────────────────────────────────────────────
    lines += [
        sep,
        "# See docs/TESTING_GUIDE.md for full instructions on running these tests.",
        sep,
    ]

    return "\n".join(lines)
