# Copyright (c) 2026 ad25343 — https://github.com/ad25343/InformaticaConversion
# Licensed under CC BY-NC 4.0. Commercial use requires written permission.
"""
Test Generator Module — Step 9
Fully deterministic — no Claude needed.

Responsibility: produce stack-appropriate test file artifacts derived from the
ACTUAL generated code (file names, model names, column names, target tables)
rather than from hardcoded assumptions.

Supported stacks: dbt, PySpark, Python (pandas), plain SQL.

Expression boundary tests (Component A, v2.13) live in expression_boundary_tests.py
and are re-exported here for backward compatibility.

NOTE ON EXECUTION (v2.13):
  The generated test files are ARTIFACTS delivered alongside the converted code.
  The conversion tool does NOT execute them.  Responsibility for running them
  lives with the data engineering team in their own environment.  See:
    docs/TESTING_GUIDE.md  — full instructions for each test type
"""
from __future__ import annotations
import re
from datetime import datetime, timezone

from ..models.schemas import (
    FieldCoverageCheck,
    TargetStack,
)
from .coverage_checker import discover_generated_artifacts  # noqa: F401
from .expression_boundary_tests import generate_expression_boundary_tests  # noqa: F401


# ─────────────────────────────────────────────────────────────────────────────
# Test file generation — driven by discovered artifacts
# ─────────────────────────────────────────────────────────────────────────────

def generate_tests_from_artifacts(
    discovered: dict,
    files: dict[str, str],
    mapped: list[dict],
    source_filters: list[dict],
    field_checks: list[FieldCoverageCheck],
    stack: TargetStack,
) -> tuple[dict[str, str], list[str]]:
    """
    Route to the correct generator based on what was actually detected in the code,
    not just the declared stack enum.
    """
    hint = discovered["stack_hint"]

    if hint == "dbt":
        return generate_dbt_tests(discovered, files, mapped, source_filters, field_checks)
    elif hint in ("pyspark",):
        return generate_pytest_tests(discovered, files, mapped, source_filters,
                                     field_checks, stack, is_spark=True)
    elif hint in ("python",):
        return generate_pytest_tests(discovered, files, mapped, source_filters,
                                     field_checks, stack, is_spark=False)
    elif hint == "sql":
        return generate_sql_tests(discovered, files, mapped, source_filters, field_checks)
    else:
        notes = [f"Test generation not yet implemented for detected stack: {hint}"]
        # Still produce coverage report
        tf, _ = write_coverage_report(files, discovered, field_checks, source_filters)
        notes.append("Coverage report generated.")
        return tf, notes


_PK_PATTERN = re.compile(r"(_key|_id|_sk)$", re.IGNORECASE)


def _dbt_not_empty_sql(fname: str, model_name: str, ts: str) -> str:
    return f"""-- Auto-generated by Informatica Conversion Tool — Step 9
-- Generated: {ts}
-- Source model file: {fname}
-- Test: assert model '{model_name}' is not empty after conversion
SELECT COUNT(*) AS row_count
FROM {{{{ ref('{model_name}') }}}}
HAVING COUNT(*) = 0
"""


def _dbt_pk_null_sql(fname: str, model_name: str, pk: str, ts: str) -> str:
    return f"""-- Auto-generated by Informatica Conversion Tool — Step 9
-- Generated: {ts}
-- Source model file: {fname}
-- Test: assert no NULLs on surrogate/primary key field '{pk}'
SELECT COUNT(*) AS null_count
FROM {{{{ ref('{model_name}') }}}}
WHERE {pk} IS NULL
HAVING COUNT(*) > 0
"""


def _dbt_schema_supplement(model_name: str, model_cols: list[str], ts: str) -> str:
    col_lines = chr(10).join(f'      - name: {c}' for c in model_cols[:20])
    return f"""# Auto-generated schema test supplement — Step 9
# Generated: {ts}
# Append these column tests to your existing schema.yml for model '{model_name}'
# Detected columns: {', '.join(model_cols)}

models:
  - name: {model_name}
    description: "Auto-generated coverage tests — review and merge into main schema.yml"
    columns:
{col_lines}
"""


def _is_pk_field(name: str) -> bool:
    """Return True if name matches a primary/surrogate key pattern."""
    return bool(_PK_PATTERN.search(name))


def _pks_from_cols(model_cols: list[str]) -> list[str]:
    """Extract PK candidate names from model column list."""
    return [c for c in model_cols if _is_pk_field(c)]


def _pks_from_mapped(mapped: list[dict]) -> list[str]:
    """Extract PK candidate names from S2T mapped records."""
    return [r["target_field"].lower() for r in mapped if _is_pk_field(r.get("target_field", ""))]


def _pk_candidates_for_model(model_cols: list[str], mapped: list[dict]) -> list[str]:
    """Find PK candidate columns from model columns, falling back to S2T records."""
    from_cols = _pks_from_cols(model_cols)
    return from_cols if from_cols else _pks_from_mapped(mapped)


def _generate_dbt_model_tests(
    fname: str,
    model_name: str,
    model_cols: list[str],
    mapped: list[dict],
    ts: str,
) -> dict[str, str]:
    """Generate test files for a single dbt model."""
    test_files: dict[str, str] = {
        f"tests/assert_{model_name}_not_empty.sql": _dbt_not_empty_sql(fname, model_name, ts),
    }
    for pk in _pk_candidates_for_model(model_cols, mapped)[:3]:
        test_files[f"tests/assert_{model_name}_{pk}_not_null.sql"] = _dbt_pk_null_sql(fname, model_name, pk, ts)
    if model_cols:
        test_files[f"tests/{model_name}_schema_supplement.yml"] = _dbt_schema_supplement(model_name, model_cols, ts)
    return test_files


def _dbt_test_summary(test_files: dict) -> str:
    """Build a note summarising how many dbt test files were generated."""
    sql_count  = sum(1 for k in test_files if k.endswith(".sql"))
    yaml_count = sum(1 for k in test_files if k.endswith(".yml"))
    return (
        f"Generated {len(test_files)} test file(s) — "
        f"{sql_count} SQL tests, {yaml_count} YAML supplements, 1 coverage report"
    )


def _dbt_test_files_for_models(sql_models: list, mapped: list[dict], ts: str) -> dict[str, str]:
    """Build test file dict for every named dbt SQL model."""
    test_files: dict[str, str] = {}
    for fname, model_name, _target_table, model_cols in sql_models:
        if model_name:
            test_files.update(_generate_dbt_model_tests(fname, model_name, model_cols, mapped, ts))
    return test_files


def generate_dbt_tests(
    discovered: dict,
    files: dict[str, str],
    mapped: list[dict],
    source_filters: list[dict],
    field_checks: list[FieldCoverageCheck],
) -> tuple[dict[str, str], list[str]]:
    """
    Generate dbt singular SQL tests and a schema test supplement,
    using the actual model names discovered from the generated code.
    """
    test_files: dict[str, str] = {}
    notes: list[str] = []
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    sql_models = discovered["sql_models"]
    if not sql_models:
        notes.append("No SQL model files found — skipping dbt singular test generation.")
    else:
        test_files.update(_dbt_test_files_for_models(sql_models, mapped, ts))

    coverage_files, _ = write_coverage_report(files, discovered, field_checks, source_filters)
    test_files.update(coverage_files)
    notes.append(_dbt_test_summary(test_files))
    return test_files, notes


def _sql_pk_fields(mapped: list[dict]) -> list[str]:
    """Extract lowercase PK field names from S2T mapped records."""
    return [
        r.get("target_field", "").lower() for r in mapped
        if re.search(r"(_key|_id|_sk)$", r.get("target_field", ""), re.IGNORECASE)
    ]


def _sql_null_assertions(pk_fields: list[str], final_table: str) -> str:
    """Build NULL-check SQL statements for PK fields."""
    lines = "\n".join(
        f"-- PK field: {f}\nSELECT COUNT(*) AS null_{f} FROM {final_table} WHERE {f} IS NULL;"
        for f in pk_fields[:5]
    )
    return lines or "-- No primary key fields detected from S2T mapping"


def _sql_field_comments(field_checks: list[FieldCoverageCheck]) -> str:
    """Build comment lines listing each field coverage status."""
    return "\n".join(
        f"  -- {'✅' if c.covered else '❌'} {c.target_field}"
        for c in field_checks
    )


def _sql_filter_comments(source_filters: list[dict]) -> str:
    """Build comment lines listing each source filter."""
    if not source_filters:
        return "-- No source filters detected"
    return "\n".join(
        f"-- Filter applied: {f['condition']} ({f['source']})"
        for f in source_filters
    )


def generate_sql_tests(
    discovered: dict,
    files: dict[str, str],
    mapped: list[dict],
    source_filters: list[dict],
    field_checks: list[FieldCoverageCheck],
) -> tuple[dict[str, str], list[str]]:
    """
    Generate plain SQL validation scripts for raw SQL / non-dbt output.
    Uses actual target table names found in the generated code.
    """
    test_files: dict[str, str] = {}
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    final_table     = discovered["final_table"] or "TARGET_TABLE"
    null_assertions = _sql_null_assertions(_sql_pk_fields(mapped), final_table)
    field_comments  = _sql_field_comments(field_checks)
    filter_comments = _sql_filter_comments(source_filters)

    row_count_script = f"""-- Auto-generated validation script — Informatica Conversion Tool Step 9
-- Generated: {ts}
-- Target table: {final_table}
-- Run these queries against your data warehouse after loading

-- ── 1. Row count ──────────────────────────────────────────────────────────────
SELECT COUNT(*) AS total_rows FROM {final_table};
-- Expected: > 0

-- ── 2. PK / Key field NULL checks ────────────────────────────────────────────
{null_assertions}

-- ── 3. Column presence (manual verification guide) ───────────────────────────
-- Verify the following columns exist in {final_table}:
{field_comments}

-- ── 4. Filter verification ────────────────────────────────────────────────────
{filter_comments}
"""
    test_files[f"tests/validate_{final_table.lower()}.sql"] = row_count_script

    coverage_files, _ = write_coverage_report(files, discovered, field_checks, source_filters)
    test_files.update(coverage_files)

    notes = [
        f"Generated SQL validation script for target table '{final_table}'. "
        "Run against your warehouse after loading to verify conversion correctness."
    ]
    return test_files, notes


_ENTRY_KEYWORDS = ("main", "run", "execute", "transform", "load", "convert")


def _is_entry_func(fn: str) -> bool:
    """Return True if fn looks like a pipeline entry-point function."""
    return any(k in fn.lower() for k in _ENTRY_KEYWORDS)


def _find_entry_in_file(fname: str, funcs: list) -> tuple:
    """Return (fname, fn) if any func is an entry-point, else (None, None)."""
    for fn in funcs:
        if _is_entry_func(fn):
            return fname, fn
    return None, None


def _fallback_entry(py_files: list) -> tuple:
    """Return (fname, func) from the last py file as a fallback."""
    if py_files:
        fname, funcs, _ = py_files[-1]
        return fname, (funcs[0] if funcs else "transform")
    return None, None


def _find_entry_point(py_files: list) -> tuple:
    """Return (entry_file, entry_func) from discovered Python files."""
    for fname, funcs, _ in py_files:
        ef, fn = _find_entry_in_file(fname, funcs)
        if fn:
            return ef, fn
    return _fallback_entry(py_files)


def _entry_labels(py_files: list) -> tuple[str, str]:
    """Return (entry_file_label, entry_func_label) with 'unknown' defaults."""
    ef, fn = _find_entry_point(py_files)
    return ef if ef else "unknown", fn if fn else "unknown"


def _pytest_spark_snippets(entry_file: str, entry_func: str) -> tuple[str, str, str]:
    """Return (imports, fixture_hint, null_check, len_check) for PySpark."""
    ef = entry_file or "your_module"
    fn = entry_func or "transform"
    imports = (
        "from pyspark.sql import SparkSession\n"
        "import pytest\n\n\n"
        "@pytest.fixture(scope='session')\n"
        "def spark():\n"
        "    return SparkSession.builder.master('local').appName('test').getOrCreate()\n"
    )
    fixture_hint = (
        f"    # Run the converted pipeline and return the output DataFrame\n"
        f"    # Example:\n"
        f"    #   from {ef.replace('/', '.').rstrip('.py')} import {fn}\n"
        f"    #   return {fn}(spark)\n"
        f"    raise NotImplementedError('Replace with actual pipeline call')"
    )
    return imports, fixture_hint, "    null_count = output_df.filter(output_df[col].isNull()).count()", "    count = output_df.count()"


def _pytest_pandas_snippets(entry_file: str, entry_func: str) -> tuple[str, str, str, str]:
    """Return (imports, fixture_hint, null_check, len_check) for pandas."""
    ef = entry_file or "your_module"
    fn = entry_func or "transform"
    fixture_hint = (
        f"    # Run the converted pipeline and return the output DataFrame\n"
        f"    # Example:\n"
        f"    #   from {ef.replace('/', '.').rstrip('.py')} import {fn}\n"
        f"    #   return {fn}()\n"
        f"    raise NotImplementedError('Replace with actual pipeline call')"
    )
    return "import pytest\nimport pandas as pd\n", fixture_hint, "    null_count = output_df[col].isna().sum()", "    count = len(output_df)"


def _field_test_block(fld: str, null_check: str) -> str:
    """Generate the two test functions for one field."""
    safe   = re.sub(r"[^A-Za-z0-9_]", "_", fld)
    is_key = bool(_PK_PATTERN.search(fld))
    hard_fail = "  # PK: hard failure" if is_key else "  # informational"
    pk_assert = (
        f"assert null_count == 0, f\"PK field '{fld}' has {{null_count}} NULLs — should be 0\""
        if is_key
        else "assert null_count >= 0  # informational — tighten for PK fields"
    )
    return f"""

def test_{safe}_present_in_output(output_df):
    \"\"\"Target field '{fld}' must exist in the output dataset.\"\"\"
    cols = [c.lower() for c in output_df.columns]
    assert '{fld}' in cols, f"Missing column '{fld}' — got: {{cols}}"


def test_{safe}_nulls(output_df):{hard_fail}
    \"\"\"Check NULL count for field '{fld}'.\"\"\"
    col = '{fld}'
    if col not in [c.lower() for c in output_df.columns]:
        pytest.skip(f"Column '{{col}}' not present — skipping null check")
{null_check}
    {pk_assert}
"""


def _filter_test_block(i: int, flt: dict, count_expr: str) -> str:
    cond  = flt["condition"]
    return f"""

def test_filter_{i}_applied(output_df):
    \"\"\"Filter from {flt['source']} should be reflected in output.

    Original filter: {cond}
    TODO: implement the actual assertion for this condition.
    \"\"\"
    {count_expr}
    assert count >= 0  # placeholder — implement real filter assertion
"""


def _count_covered(field_checks: list[FieldCoverageCheck]) -> int:
    """Count covered field checks."""
    return sum(1 for c in field_checks if c.covered)


def _coverage_summary_comment(field_checks: list[FieldCoverageCheck]) -> str:
    """Build the coverage comment block for the pytest file header."""
    return "\n".join(
        f"#   {'✅' if c.covered else '❌'}  {c.target_field}"
        f"{' ← NOT FOUND IN CODE' if not c.covered else ''}"
        for c in field_checks
    )


def _collect_field_list(discovered: dict, mapped: list[dict]) -> tuple:
    """Merge code-discovered columns with S2T fields (deduped)."""
    all_code_cols: list[str] = []
    for _, _, _, cols in discovered["sql_models"]:
        all_code_cols.extend(cols)
    s2t_fields = [r.get("target_field", "").lower() for r in mapped if r.get("target_field")]
    return list(dict.fromkeys(all_code_cols + s2t_fields)), all_code_cols


def generate_pytest_tests(
    discovered: dict,
    files: dict[str, str],
    mapped: list[dict],
    source_filters: list[dict],
    field_checks: list[FieldCoverageCheck],
    stack: TargetStack,
    is_spark: bool,
) -> tuple[dict[str, str], list[str]]:
    """
    Generate a pytest suite for Python / PySpark output.
    Uses actual function names and DataFrame variables found in the generated code.
    """
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    ef_label, fn_label = _entry_labels(discovered["python_files"])
    field_list, all_code_cols = _collect_field_list(discovered, mapped)

    if is_spark:
        imports, fixture_hint, null_check, len_check = _pytest_spark_snippets(ef_label, fn_label)
        count_expr = "count = output_df.count()"
    else:
        imports, fixture_hint, null_check, len_check = _pytest_pandas_snippets(ef_label, fn_label)
        count_expr = "count = len(output_df)"

    field_tests  = "".join(_field_test_block(fld, null_check) for fld in field_list[:30])
    filter_tests = "".join(_filter_test_block(i + 1, flt, count_expr) for i, flt in enumerate(source_filters))

    covered_count    = _count_covered(field_checks)
    coverage_comment = _coverage_summary_comment(field_checks)

    content = f'''"""
Auto-generated test suite — Informatica Conversion Tool Step 9
Generated:  {ts}
Stack:      {stack.value}
Entry file: {ef_label}
Entry func: {fn_label}

Field coverage summary ({covered_count}/{len(field_checks)} covered):
{coverage_comment}
"""
{imports}

# ─── Fixture: load the converted pipeline output ───────────────────────────────
@pytest.fixture
def output_df():
    """
    Load the output of the converted pipeline.
    Replace this with actual code that runs your converted script/function.
    """
{fixture_hint}


# ─── Field presence & null checks (auto-generated from S2T + discovered columns) ──
{field_tests}

# ─── Filter condition checks (from Informatica source filters) ─────────────────
{filter_tests}

# ─── Row count sanity check ─────────────────────────────────────────────────────
def test_output_not_empty(output_df):
    """Output dataset must contain at least one row after conversion."""
{len_check}
    assert count > 0, "Output dataset is empty — conversion may have produced no rows"
'''

    test_files: dict[str, str] = {"tests/test_conversion.py": content}
    coverage_files, _ = write_coverage_report(files, discovered, field_checks, source_filters)
    test_files.update(coverage_files)

    col_source = "actual column names discovered in code" if all_code_cols else "S2T target fields"
    notes = [
        f"Generated tests/test_conversion.py with {len(field_list[:30])} field tests "
        f"using {col_source}. "
        "Fill in the output_df fixture to run."
    ]
    return test_files, notes


# ─────────────────────────────────────────────────────────────────────────────
# Coverage report (always produced, stack-agnostic)
# ─────────────────────────────────────────────────────────────────────────────

def _coverage_note(c: FieldCoverageCheck) -> str:
    """Return the inline note for a missing field, or empty string."""
    if c.note and not c.covered:
        return f" _{c.note}_"
    return ""


def _coverage_row(c: FieldCoverageCheck) -> str:
    """Render a single field coverage check as a markdown table row."""
    status = "✅" if c.covered else "❌"
    found  = ", ".join(c.found_in_files) if c.found_in_files else "—"
    table  = c.target_table if c.target_table else "—"
    return f"| {status} | `{c.target_field}` | {table} | {found}{_coverage_note(c)} |"


def _field_coverage_rows(field_checks: list[FieldCoverageCheck]) -> list[str]:
    """Render each field check as a markdown table row."""
    return [_coverage_row(c) for c in field_checks]


def _sql_model_row(fname: str, model_name: str, target_table: str) -> str:
    tbl = target_table or "?"
    return f"| `{fname}` | SQL model | {model_name} → {tbl} |"


def _yaml_schema_row(fname: str, model_names: list[str]) -> str:
    label = ", ".join(model_names) or "?"
    return f"| `{fname}` | YAML schema | {label} |"


def _python_file_row(fname: str, funcs: list[str]) -> str:
    label = ", ".join(funcs[:5]) or "?"
    return f"| `{fname}` | Python | funcs: {label} |"


def _generated_file_rows(discovered: dict) -> list[str]:
    """Render discovered file entries as markdown table rows."""
    rows: list[str] = []
    for fname, model_name, target_table, _cols in discovered["sql_models"]:
        rows.append(_sql_model_row(fname, model_name, target_table))
    for fname, model_names in discovered["yaml_schemas"]:
        rows.append(_yaml_schema_row(fname, model_names))
    for fname, funcs, _ in discovered["python_files"]:
        rows.append(_python_file_row(fname, funcs))
    return rows


def _filter_coverage_rows(source_filters: list[dict]) -> list[str]:
    """Render source filter rows for the coverage report."""
    if source_filters:
        return [f"| ⬜ | `{flt['condition']}` | {flt['source']} |" for flt in source_filters]
    return ["| — | No source filters detected | — |"]


def _coverage_pct(field_checks: list[FieldCoverageCheck]) -> tuple[int, int, float]:
    """Return (covered, total, pct) for field coverage."""
    covered = sum(1 for c in field_checks if c.covered)
    total = len(field_checks)
    pct = round(100 * covered / total, 1) if total else 100.0
    return covered, total, pct


def _cols_line(all_cols: list) -> str:
    """Return the columns display line for the coverage report."""
    return ", ".join(all_cols) if all_cols else "(none detected)"


def write_coverage_report(
    files: dict[str, str],
    discovered: dict,
    field_checks: list[FieldCoverageCheck],
    source_filters: list[dict],
) -> tuple[dict[str, str], list[str]]:
    """
    Produce a markdown coverage report that summarises what was found
    in the *actual* generated files.
    """
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    covered, total, pct = _coverage_pct(field_checks)
    all_cols    = discovered["all_columns"]
    final_model = discovered["final_model"] or "N/A"

    lines = [
        "# Conversion Coverage Report",
        f"Generated: {ts}",
        f"Detected stack: **{discovered['stack_hint']}**",
        f"Final model/table: **{final_model}**",
        "",
        f"## Field Coverage — {pct}% ({covered}/{total} fields)",
        "| Status | Target Field | Target Table | Found In |",
        "|--------|-------------|-------------|----------|",
    ]
    lines.extend(_field_coverage_rows(field_checks))
    lines += [
        "",
        "## Columns Discovered in Generated Code",
        f"The following {len(all_cols)} column name(s) were parsed from the generated files:",
        "",
        "```",
        _cols_line(all_cols),
        "```",
        "",
        "## Generated Files",
        "| File | Type | Model/Table |",
        "|------|------|------------|",
    ]
    lines.extend(_generated_file_rows(discovered))
    lines += [
        "",
        "## Source Filter Coverage",
        "| Status | Filter Condition | Source |",
        "|--------|-----------------|--------|",
    ]
    lines.extend(_filter_coverage_rows(source_filters))

    return {"tests/COVERAGE_REPORT.md": "\n".join(lines)}, []


# ─────────────────────────────────────────────────────────────────────────────
# Private aliases kept for callers that used leading-underscore names
# ─────────────────────────────────────────────────────────────────────────────
_generate_tests_from_artifacts      = generate_tests_from_artifacts
_generate_dbt_tests                 = generate_dbt_tests
_generate_sql_tests                 = generate_sql_tests
_generate_pytest_tests              = generate_pytest_tests
_write_coverage_report              = write_coverage_report
_generate_expression_boundary_tests = generate_expression_boundary_tests
