# Copyright (c) 2026 ad25343 — https://github.com/ad25343/InformaticaConversion
# Licensed under CC BY-NC 4.0. Commercial use requires written permission.
"""
Test Generator Module — Step 9
Fully deterministic — no Claude needed.

Responsibility: produce stack-appropriate test file artifacts derived from the
ACTUAL generated code (file names, model names, column names, target tables)
rather than from hardcoded assumptions.

Supported stacks: dbt, PySpark, Python (pandas), plain SQL.

Expression boundary tests (Component A, v2.13) live in expression_boundary_tests.py
and are re-exported here for backward compatibility.

NOTE ON EXECUTION (v2.13):
  The generated test files are ARTIFACTS delivered alongside the converted code.
  The conversion tool does NOT execute them.  Responsibility for running them
  lives with the data engineering team in their own environment.  See:
    docs/TESTING_GUIDE.md  — full instructions for each test type
"""
from __future__ import annotations
import re
from datetime import datetime, timezone

from ..models.schemas import (
    FieldCoverageCheck,
    TargetStack,
)
from .coverage_checker import discover_generated_artifacts  # noqa: F401
from .expression_boundary_tests import generate_expression_boundary_tests  # noqa: F401


# ─────────────────────────────────────────────────────────────────────────────
# Test file generation — driven by discovered artifacts
# ─────────────────────────────────────────────────────────────────────────────

def generate_tests_from_artifacts(
    discovered: dict,
    files: dict[str, str],
    mapped: list[dict],
    source_filters: list[dict],
    field_checks: list[FieldCoverageCheck],
    stack: TargetStack,
) -> tuple[dict[str, str], list[str]]:
    """
    Route to the correct generator based on what was actually detected in the code,
    not just the declared stack enum.
    """
    hint = discovered["stack_hint"]

    if hint == "dbt":
        return generate_dbt_tests(discovered, files, mapped, source_filters, field_checks)
    elif hint in ("pyspark",):
        return generate_pytest_tests(discovered, files, mapped, source_filters,
                                     field_checks, stack, is_spark=True)
    elif hint in ("python",):
        return generate_pytest_tests(discovered, files, mapped, source_filters,
                                     field_checks, stack, is_spark=False)
    elif hint == "sql":
        return generate_sql_tests(discovered, files, mapped, source_filters, field_checks)
    else:
        notes = [f"Test generation not yet implemented for detected stack: {hint}"]
        # Still produce coverage report
        tf, _ = write_coverage_report(files, discovered, field_checks, source_filters)
        notes.append("Coverage report generated.")
        return tf, notes


def generate_dbt_tests(
    discovered: dict,
    files: dict[str, str],
    mapped: list[dict],
    source_filters: list[dict],
    field_checks: list[FieldCoverageCheck],
) -> tuple[dict[str, str], list[str]]:
    """
    Generate dbt singular SQL tests and a schema test supplement,
    using the actual model names discovered from the generated code.
    """
    test_files: dict[str, str] = {}
    notes: list[str] = []
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # Use discovered model names (from actual SQL files), not assumed names
    sql_models = discovered["sql_models"]  # [(fname, model_name, target_table, cols)]

    if not sql_models:
        notes.append("No SQL model files found — skipping dbt singular test generation.")
    else:
        for fname, model_name, target_table, model_cols in sql_models:
            if not model_name:
                continue

            # Singular test: row count > 0
            not_empty = f"""-- Auto-generated by Informatica Conversion Tool — Step 9
-- Generated: {ts}
-- Source model file: {fname}
-- Test: assert model '{model_name}' is not empty after conversion
SELECT COUNT(*) AS row_count
FROM {{{{ ref('{model_name}') }}}}
HAVING COUNT(*) = 0
"""
            test_files[f"tests/assert_{model_name}_not_empty.sql"] = not_empty

            # PK not-null tests — use ACTUAL columns found in this model
            # Prefer columns that end in _key, _id, or _sk (surrogate key)
            pk_candidates = [
                c for c in model_cols
                if re.search(r"(_key|_id|_sk)$", c, re.IGNORECASE)
            ]
            # Fall back to S2T records if no PK found in parsed columns
            if not pk_candidates:
                pk_candidates = [
                    r["target_field"].lower() for r in mapped
                    if re.search(r"(_key|_id|_sk)$",
                                 r.get("target_field", ""), re.IGNORECASE)
                ]
            for pk in pk_candidates[:3]:
                null_test = f"""-- Auto-generated by Informatica Conversion Tool — Step 9
-- Generated: {ts}
-- Source model file: {fname}
-- Test: assert no NULLs on surrogate/primary key field '{pk}'
SELECT COUNT(*) AS null_count
FROM {{{{ ref('{model_name}') }}}}
WHERE {pk} IS NULL
HAVING COUNT(*) > 0
"""
                test_files[f"tests/assert_{model_name}_{pk}_not_null.sql"] = null_test

            # Schema test additions — write a supplementary YAML only for this model
            # using the columns we actually discovered in the SQL
            if model_cols:
                schema_supplement = f"""# Auto-generated schema test supplement — Step 9
# Generated: {ts}
# Append these column tests to your existing schema.yml for model '{model_name}'
# Detected columns: {', '.join(model_cols)}

models:
  - name: {model_name}
    description: "Auto-generated coverage tests — review and merge into main schema.yml"
    columns:
{chr(10).join(f'      - name: {c}' for c in model_cols[:20])}
"""
                test_files[f"tests/{model_name}_schema_supplement.yml"] = schema_supplement

    # Coverage report (always generated)
    coverage_files, _ = write_coverage_report(files, discovered, field_checks, source_filters)
    test_files.update(coverage_files)

    notes.append(
        f"Generated {len(test_files)} test file(s) — "
        f"{len([k for k in test_files if k.endswith('.sql')])} SQL tests, "
        f"{len([k for k in test_files if k.endswith('.yml')])} YAML supplements, "
        f"1 coverage report"
    )
    return test_files, notes


def generate_sql_tests(
    discovered: dict,
    files: dict[str, str],
    mapped: list[dict],
    source_filters: list[dict],
    field_checks: list[FieldCoverageCheck],
) -> tuple[dict[str, str], list[str]]:
    """
    Generate plain SQL validation scripts for raw SQL / non-dbt output.
    Uses actual target table names found in the generated code.
    """
    test_files: dict[str, str] = {}
    notes: list[str] = []
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    final_table = discovered["final_table"] or "TARGET_TABLE"

    pk_fields = [
        r.get("target_field", "").lower() for r in mapped
        if re.search(r"(_key|_id|_sk)$", r.get("target_field", ""), re.IGNORECASE)
    ]

    null_assertions = "\n".join(
        f"-- PK field: {f}\nSELECT COUNT(*) AS null_{f} FROM {final_table} WHERE {f} IS NULL;"
        for f in pk_fields[:5]
    )
    field_comments = "\n".join(
        f"  -- {'✅' if c.covered else '❌'} {c.target_field}"
        for c in field_checks
    )

    row_count_script = f"""-- Auto-generated validation script — Informatica Conversion Tool Step 9
-- Generated: {ts}
-- Target table: {final_table}
-- Run these queries against your data warehouse after loading

-- ── 1. Row count ──────────────────────────────────────────────────────────────
SELECT COUNT(*) AS total_rows FROM {final_table};
-- Expected: > 0

-- ── 2. PK / Key field NULL checks ────────────────────────────────────────────
{null_assertions or "-- No primary key fields detected from S2T mapping"}

-- ── 3. Column presence (manual verification guide) ───────────────────────────
-- Verify the following columns exist in {final_table}:
{field_comments}

-- ── 4. Filter verification ────────────────────────────────────────────────────
{chr(10).join(f"-- Filter applied: {f['condition']} ({f['source']})" for f in source_filters)
  or "-- No source filters detected"}
"""
    test_files[f"tests/validate_{final_table.lower()}.sql"] = row_count_script

    # Coverage report
    coverage_files, _ = write_coverage_report(files, discovered, field_checks, source_filters)
    test_files.update(coverage_files)

    notes.append(
        f"Generated SQL validation script for target table '{final_table}'. "
        "Run against your warehouse after loading to verify conversion correctness."
    )
    return test_files, notes


def generate_pytest_tests(
    discovered: dict,
    files: dict[str, str],
    mapped: list[dict],
    source_filters: list[dict],
    field_checks: list[FieldCoverageCheck],
    stack: TargetStack,
    is_spark: bool,
) -> tuple[dict[str, str], list[str]]:
    """
    Generate a pytest suite for Python / PySpark output.
    Uses actual function names and DataFrame variables found in the generated code.
    """
    notes: list[str] = []
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # Discover actual function names and file structure
    py_files   = discovered["python_files"]  # [(fname, funcs, df_vars)]
    entry_file = None
    entry_func = None

    for fname, funcs, _ in py_files:
        for fn in funcs:
            if any(k in fn.lower() for k in
                   ("main", "run", "execute", "transform", "load", "convert")):
                entry_file = fname
                entry_func = fn
                break
        if entry_func:
            break

    if not entry_file and py_files:
        entry_file, funcs, _ = py_files[-1]
        entry_func = funcs[0] if funcs else "transform"

    # Use columns found across all SQL models, fall back to S2T fields
    all_code_cols: list[str] = []
    for _, _, _, cols in discovered["sql_models"]:
        all_code_cols.extend(cols)

    # For field tests: use actual columns found in code where possible,
    # then supplement with S2T target fields
    s2t_fields = [r.get("target_field", "").lower()
                  for r in mapped if r.get("target_field")]
    # Merge: code-discovered columns first, then S2T (dedup)
    field_list = list(dict.fromkeys(all_code_cols + s2t_fields))

    if is_spark:
        imports = (
            "from pyspark.sql import SparkSession\n"
            "import pytest\n\n\n"
            "@pytest.fixture(scope='session')\n"
            "def spark():\n"
            "    return SparkSession.builder.master('local').appName('test').getOrCreate()\n"
        )
        fixture_hint = (
            f"    # Run the converted pipeline and return the output DataFrame\n"
            f"    # Example:\n"
            f"    #   from {(entry_file or 'your_module').replace('/', '.').rstrip('.py')} import {entry_func or 'transform'}\n"
            f"    #   return {entry_func or 'transform'}(spark)\n"
            f"    raise NotImplementedError('Replace with actual pipeline call')"
        )
        null_check = (
            "    null_count = output_df.filter(output_df[col].isNull()).count()"
        )
        len_check = "    count = output_df.count()"
    else:
        imports = "import pytest\nimport pandas as pd\n"
        fixture_hint = (
            f"    # Run the converted pipeline and return the output DataFrame\n"
            f"    # Example:\n"
            f"    #   from {(entry_file or 'your_module').replace('/', '.').rstrip('.py')} import {entry_func or 'transform'}\n"
            f"    #   return {entry_func or 'transform'}()\n"
            f"    raise NotImplementedError('Replace with actual pipeline call')"
        )
        null_check = "    null_count = output_df[col].isna().sum()"
        len_check  = "    count = len(output_df)"

    field_tests = ""
    for fld in field_list[:30]:  # cap to avoid huge files
        safe = re.sub(r"[^A-Za-z0-9_]", "_", fld)
        is_key = bool(re.search(r"(_key|_id|_sk)$", fld, re.IGNORECASE))
        hard_fail = "  # PK: hard failure" if is_key else "  # informational"
        pk_assert = (f"assert null_count == 0, "
                     f"f\"PK field '{fld}' has {{null_count}} NULLs — should be 0\""
                     if is_key
                     else "assert null_count >= 0  # informational — tighten for PK fields")
        field_tests += f"""

def test_{safe}_present_in_output(output_df):
    \"\"\"Target field '{fld}' must exist in the output dataset.\"\"\"
    cols = [c.lower() for c in output_df.columns]
    assert '{fld}' in cols, f"Missing column '{fld}' — got: {{cols}}"


def test_{safe}_nulls(output_df):{hard_fail}
    \"\"\"Check NULL count for field '{fld}'.\"\"\"
    col = '{fld}'
    if col not in [c.lower() for c in output_df.columns]:
        pytest.skip(f"Column '{{col}}' not present — skipping null check")
{null_check}
    {pk_assert}
"""

    filter_tests = ""
    for i, flt in enumerate(source_filters):
        cond = flt["condition"]
        safe_i = i + 1
        filter_tests += f"""

def test_filter_{safe_i}_applied(output_df):
    \"\"\"Filter from {flt['source']} should be reflected in output.

    Original filter: {cond}
    TODO: implement the actual assertion for this condition.
    \"\"\"
    # Verify the filter reduced rows (compare against unfiltered count if available)
    {"count = output_df.count()" if is_spark else "count = len(output_df)"}
    assert count >= 0  # placeholder — implement real filter assertion
"""

    coverage_comment = "\n".join(
        f"#   {'✅' if c.covered else '❌'}  {c.target_field}"
        f"{' ← NOT FOUND IN CODE' if not c.covered else ''}"
        for c in field_checks
    )

    content = f'''"""
Auto-generated test suite — Informatica Conversion Tool Step 9
Generated:  {ts}
Stack:      {stack.value}
Entry file: {entry_file or "unknown"}
Entry func: {entry_func or "unknown"}

Field coverage summary ({sum(1 for c in field_checks if c.covered)}/{len(field_checks)} covered):
{coverage_comment}
"""
{imports}

# ─── Fixture: load the converted pipeline output ───────────────────────────────
@pytest.fixture
def output_df():
    """
    Load the output of the converted pipeline.
    Replace this with actual code that runs your converted script/function.
    """
{fixture_hint}


# ─── Field presence & null checks (auto-generated from S2T + discovered columns) ──
{field_tests}

# ─── Filter condition checks (from Informatica source filters) ─────────────────
{filter_tests}

# ─── Row count sanity check ─────────────────────────────────────────────────────
def test_output_not_empty(output_df):
    """Output dataset must contain at least one row after conversion."""
{len_check}
    assert count > 0, "Output dataset is empty — conversion may have produced no rows"
'''

    test_files: dict[str, str] = {"tests/test_conversion.py": content}

    # Coverage report
    coverage_files, _ = write_coverage_report(files, discovered, field_checks, source_filters)
    test_files.update(coverage_files)

    notes.append(
        f"Generated tests/test_conversion.py with {len(field_list[:30])} field tests "
        f"using {'actual column names discovered in code' if all_code_cols else 'S2T target fields'}. "
        "Fill in the output_df fixture to run."
    )
    return test_files, notes


# ─────────────────────────────────────────────────────────────────────────────
# Coverage report (always produced, stack-agnostic)
# ─────────────────────────────────────────────────────────────────────────────

def write_coverage_report(
    files: dict[str, str],
    discovered: dict,
    field_checks: list[FieldCoverageCheck],
    source_filters: list[dict],
) -> tuple[dict[str, str], list[str]]:
    """
    Produce a markdown coverage report that summarises what was found
    in the *actual* generated files.
    """
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    covered   = sum(1 for c in field_checks if c.covered)
    total     = len(field_checks)
    pct       = round(100 * covered / total, 1) if total else 100.0

    stack_hint  = discovered["stack_hint"]
    sql_models  = discovered["sql_models"]
    final_model = discovered["final_model"] or "N/A"
    all_cols    = discovered["all_columns"]

    lines = [
        "# Conversion Coverage Report",
        f"Generated: {ts}",
        f"Detected stack: **{stack_hint}**",
        f"Final model/table: **{final_model}**",
        "",
        f"## Field Coverage — {pct}% ({covered}/{total} fields)",
        "| Status | Target Field | Target Table | Found In |",
        "|--------|-------------|-------------|----------|",
    ]
    for c in field_checks:
        status = "✅" if c.covered else "❌"
        found  = ", ".join(c.found_in_files) if c.found_in_files else "—"
        note   = f" _{c.note}_" if c.note and not c.covered else ""
        lines.append(f"| {status} | `{c.target_field}` | {c.target_table or '—'} | {found}{note} |")

    lines += [
        "",
        "## Columns Discovered in Generated Code",
        f"The following {len(all_cols)} column name(s) were parsed from the generated files:",
        "",
        "```",
        ", ".join(all_cols) if all_cols else "(none detected)",
        "```",
        "",
        "## Generated Files",
        "| File | Type | Model/Table |",
        "|------|------|------------|",
    ]
    for fname, model_name, target_table, cols in sql_models:
        lines.append(f"| `{fname}` | SQL model | {model_name} → {target_table or '?'} |")
    for fname, model_names in discovered["yaml_schemas"]:
        lines.append(f"| `{fname}` | YAML schema | {', '.join(model_names) or '?'} |")
    for fname, funcs, _ in discovered["python_files"]:
        lines.append(f"| `{fname}` | Python | funcs: {', '.join(funcs[:5]) or '?'} |")

    lines += [
        "",
        "## Source Filter Coverage",
        "| Status | Filter Condition | Source |",
        "|--------|-----------------|--------|",
    ]
    if source_filters:
        for flt in source_filters:
            lines.append(f"| ⬜ | `{flt['condition']}` | {flt['source']} |")
    else:
        lines.append("| — | No source filters detected | — |")

    return {"tests/COVERAGE_REPORT.md": "\n".join(lines)}, []


# ─────────────────────────────────────────────────────────────────────────────
# Private aliases kept for callers that used leading-underscore names
# ─────────────────────────────────────────────────────────────────────────────
_generate_tests_from_artifacts      = generate_tests_from_artifacts
_generate_dbt_tests                 = generate_dbt_tests
_generate_sql_tests                 = generate_sql_tests
_generate_pytest_tests              = generate_pytest_tests
_write_coverage_report              = write_coverage_report
_generate_expression_boundary_tests = generate_expression_boundary_tests
